---

- name: download {{ virtio_win_iso_name }}
  ansible.windows.win_get_url:
    url: '{{ virtio_win_iso_url }}'
    force: false
    dest: '{{ ansible_env.TEMP }}\{{ virtio_win_iso_name }}'
  notify:
    - delete downloaded

- name: mount {{ virtio_win_iso_name }}
  community.windows.win_disk_image:
    image_path: '{{ ansible_env.TEMP }}\{{ virtio_win_iso_name }}'
  register: win_disk_image
  until: win_disk_image is success
  delay: 3
  retries: 5
  notify:
    - unmount
  when:
    - ('Windows Server 2008' not in ansible_distribution)
    - ('Windows 7' not in ansible_distribution)

- name: extract iso
  ansible.builtin.include_tasks: extract_iso.yml
  when: ('Windows Server 2008' in ansible_distribution) or ('Windows 7' in ansible_distribution)
