---

- name: ensure Chocolatey CLI v1.4.0 is available
  chocolatey.chocolatey.win_chocolatey:
    name: chocolatey
    state: present
    version: '1.4.0'
  register: install_chocolatey
  until: install_chocolatey is success
  delay: 3
  retries: 5
  notify:
    - remove chocolatey

- name: extract iso file with 7-zip
  block:
    - name: install 7-zip
      chocolatey.chocolatey.win_chocolatey:
        name: 7zip
        state: present
      register: install_7zip
      until: install_7zip is success
      delay: 3
      retries: 5

    - name: ensure temp directory exists for iso
      ansible.windows.win_file:
        path: '{{ ansible_env.TEMP }}\virtio_iso_extract'
        state: directory

    - name: extract iso
      ansible.windows.win_shell: >
        7z.exe x -y '{{ ansible_env.TEMP }}\{{ virtio_win_iso_name }}' -o'{{ ansible_env.TEMP }}\virtio_iso_extract'

  always:
    - name: remove 7-zip
      chocolatey.chocolatey.win_chocolatey:
        name: 7zip
        state: absent
