---

- name: get qemu guest service information
  ansible.windows.win_service_info:
    name: QEMU-GA
  register: qemu_guest_service_info

- name: set qemu guest service status
  ansible.builtin.set_fact:
    qemu_guest_service_status: "{{ qemu_guest_service_info }}"

- name: install qemu guest agent and check results
  block:
    - name: install qemu guest agent
      ansible.builtin.include_tasks: qemu_agent.yml

    - name: reboot and retry if needed
      block:
        - name: reboot the system
          ansible.windows.win_reboot:

        - name: install qemu guest agent (retry)
          ansible.builtin.include_tasks: qemu_agent.yml
      when:
        - qemu_guest_installation_status.rc is defined
        - qemu_guest_installation_status.rc == 1603

    - name: get qemu guest service information
      ansible.windows.win_service_info:
        name: QEMU-GA
      register: qemu_guest_service_info_post_install

    - name: set qemu guest service status after installation
      ansible.builtin.set_fact:
        qemu_guest_service_status: "{{ qemu_guest_service_info_post_install }}"
  when: not qemu_guest_service_status.exists

- name: show qemu guest service status
  ansible.builtin.debug:
    msg: "{{ qemu_guest_service_status.services[0].state }}"
  when:
    - qemu_guest_service_status is defined
    - qemu_guest_service_status.exists
    - qemu_guest_service_status.services | length
