---

- name: Get list of all drivers
  win_command: driverquery /V
  changed_when: false
  register: driver_list

- name: Check if Red Hat certificate is not already installed
  win_shell: 'Get-ChildItem -Path Cert:\LocalMachine\TrustedPublisher'
  changed_when: false
  register: cert_check

- name: Download {{ virtio_win_iso_name }}
  win_get_url:
    url: "{{ virtio_win_iso_url }}"
    force: false
    dest: "{{ ansible_env.TEMP }}\\{{ virtio_win_iso_name }}"
  notify:
    - Delete downloaded

- name: Mount {{ virtio_win_iso_name }}
  win_disk_image:
    image_path: "{{ ansible_env.TEMP }}\\{{ virtio_win_iso_name }}"
  register: win_disk_image
  notify:
    - Unmount

- name: Set the virtio_win_iso_path and virtio_win_virtio_path
  set_fact:
    virtio_win_iso_path: "{{ win_disk_image.mount_path }}"
    virtio_win_virtio_path: "{{ win_disk_image.mount_path + '\\virtio' if virtio_win_ovirt else win_disk_image.mount_path }}"
    virtio_win_iso_name: "{{ virtio_win_iso_name }}"

- include_tasks: install_cert.yml
  when: cert_check.stdout is not search("Red Hat")

- include_tasks: install_drivers.yml