---

- name: Download {{ virtio_msi_name }}
  win_get_url:
    url: "{{ virtio_msi_url }}"
    force: false
    dest: '{{ ansible_env.TEMP }}\{{ virtio_msi_name }}'

- name: Ensure temp directory exists for msi
  win_file:
    path: '{{ ansible_env.TEMP }}\virtio_msi_extract'
    state: directory

- name: Extract msi package
  win_shell: >
    msiexec /a '{{ ansible_env.TEMP }}\{{ virtio_msi_name }}'
    /qb TARGETDIR='{{ ansible_env.TEMP }}\virtio_msi_extract'

- name: Set the virtio_msi_path
  set_fact:
    virtio_msi_path: '{{ ansible_env.TEMP }}\virtio_msi_extract\Virtio-Win'

- name: Set the virtio_win_virtio_path
  set_fact:
    virtio_win_virtio_path: "{{ virtio_msi_path + '\\virtio' if virtio_win_ovirt else virtio_msi_path }}"

- include_tasks: install_cert_from_msi.yml
  when: cert_check.stdout is not search("Red Hat")

- name: Install Virtio MSI package
  win_shell: 'msiexec /i {{ ansible_env.TEMP }}\{{ virtio_msi_name }} /qn /norestart'