---

- name: Download {{ virtio_win_iso_name }}
  win_get_url:
    url: "{{ virtio_win_iso_url }}"
    force: false
    dest: "{{ ansible_env.TEMP }}\\{{ virtio_win_iso_name }}"

- name: Mount {{ virtio_win_iso_name }}
  win_disk_image:
    image_path: "{{ ansible_env.TEMP }}\\{{ virtio_win_iso_name }}"
  register: win_disk_image

- name: Set the virtio_win_iso_path and virtio_win_virtio_path
  set_fact:
    virtio_win_iso_path: "{{ win_disk_image.mount_path }}"
    virtio_win_virtio_path: "{{ win_disk_image.mount_path + '\\virtio' if virtio_win_ovirt else win_disk_image.mount_path }}"

- include_tasks: install_cert.yml
  when: cert_check.stdout is not search("Red Hat")

- include_tasks: install_drivers.yml