---

- name: install the Virtio Drivers
  ansible.windows.win_command: >
    pnputil -i -a
    \"{{ virtio_win_virtio_path }}\\{{ item }}\\{{ virtio_driver_directory }}\\{{ ansible_env.PROCESSOR_ARCHITECTURE | lower }}\\*.inf\"
  when: driver_list.stdout is not search(item | lower)
  failed_when: false
  loop:
    - NetKVM
    - viostor
    - "{{ qxl_driver }}"
    - Balloon
    - viorng
    - vioserial
    - vioinput
    - vioscsi
    - pvpanic
