---

- name: check new version of virtio
  ansible.builtin.uri:
    url: "{{ virtio_changelog_url }}"
    return_content: true
    validate_certs: false
  register: register_virtio_changelog
  failed_when: false
  delegate_to: localhost
  become: false
  vars:
    ansible_connection: local

- name: set virtio version facts
  ansible.builtin.set_fact:
    virtio_version: "{{ register_virtio_changelog.content | regex_search(virtio_changelog_query) | default('0.0') }}"

- name: download virtio iso
  ansible.builtin.include_tasks: download.yml
  when:
    - virtio_iso_mount_drive | length == 0
    - (ansible_virtio_version | default()) != virtio_version

- name: install virtio drivers and guest agent
  block:
    - name: install virtio drivers
      ansible.builtin.include_tasks: install.yml

    - name: install qemu guest agent
      ansible.builtin.include_tasks: install_agent.yml
      when:
        - virtio_install_guest_agent | bool
        - ansible_kernel is version('10', '>=')
  when: virtio_iso_mount_drive | length > 0 or (ansible_virtio_version | default()) != virtio_version
